default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: usabi_db
  username: <%= ENV["username_postgres"] %>
  password: <%= ENV["password_postgres"] %>
  host: <%= ENV["host_postgres"] %>
  port: <%= ENV["port_postgres"] %>

production:
  <<: *default
  database: backend_production
  username: backend
  password: <%= ENV["BACKEND_DATABASE_PASSWORD"] %>

test:
  <<: *default
  database: backend_test
  username: <%= ENV["BACKEND_DATABASE_USERNAME"] %>
  password: <%= ENV["BACKEND_DATABASE_PASSWORD"] %>
  host: <%= ENV["BACKEND_DATABASE_HOST"] %>
  port: <%= ENV["BACKEND_DATABASE_PORT"] %>
